### ISSUE TITLE
rægænum?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#15]
В словаре есть rægænun, но в базе есть и rægænun, и rægænum.
![image](https://user-images.githubusercontent.com/13102259/156568858-0f032fa0-677d-4481-aae4-e718684098ed.png)
Верно ли, что rægænum появилось случайно и его надо удалить?
![image](https://user-images.githubusercontent.com/13102259/156568887-1b5121dc-a9a6-4554-8a74-e5f7ba443d5e.png)

**Comment by obelyaev** [comment]
Да, случайно. Но надо найти слова, которые на это слово ссылаются, и там поменять ссылку. Скорее всего, кто-то внёс слово по ошибке по ссылке в первом томе.

**Comment by obelyaev** [comment]
Удалили лишнее слово и исправил на него ссылку.
