### ISSUE TITLE
re?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#20]
вот тут с одной стороны явный re, еще и с несколькими значениями
а с другой как будто хочется, чтобы это было отсылкой на соответствующую статью?
![image](https://user-images.githubusercontent.com/48504970/156912293-9426099d-402c-4743-8822-26c2a9957a15.png)

**Comment by solanum-tuberosum** [comment]
а можно делать re, а внутри ставить ref, я так делала в каких-то словах

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/156917287-4d642386-f3fc-4567-8e14-c39ea6896c04.png)
Сделала вот так

**Comment by obelyaev** [comment]
Да, наверное правильно. Хотя, конечно, это дублирование информации, так что и необязательно re создавать. Но раз создали, то и хорошо.
