### ISSUE TITLE
re или comment? w или mentioned?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#22]
![image](https://user-images.githubusercontent.com/13102259/156915343-8fe9bcee-d1f2-4c4d-9bb8-ccee3e2b308c.png)
næræmon и Ræmontæ сделала re, Ræmon bon сделала комментом
![image](https://user-images.githubusercontent.com/13102259/156915380-abeec075-78ec-49e2-b70a-cf7b12b65534.png)
в этимологии Ræmon и Ræmontæ сделала просто w, это правильно?..

**Comment by obelyaev** [comment]
Да, правильно, мне кажется!
