### ISSUE TITLE
дигорский вариант полностью в скобочках...

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#25]
![image](https://user-images.githubusercontent.com/48504970/157002222-829830fd-956b-4a6d-bc35-55f119a0eb90.png)
Мы ведь пока так не умеем?

**Comment by jvsntsn** [comment]
Это точно не единичный случай...
![image](https://user-images.githubusercontent.com/48504970/157002759-8cf4f7b9-8adb-4022-bd4c-c1c99dbc9f32.png)

**Comment by obelyaev** [comment]
Хм, но обратите внимание, что оба варианта – однокоренные. Он в скобках, видимо, потому, что это не вполне когнаты. Можно, конечно, просто тупо сделать скобки в дигорской форме, но это как-то не информативно. Я могу сделать отдельный тип варианта: @type = dialectal-parentheses (но, кстати, это никак не мешает переводить, т.к. перевод это не затрагивает).

**Comment by obelyaev** [comment]
Поменял концепцию скобочек. ВАЖНО: теперь нет @type=parens, то есть варианты в скобках всё равно имеют @type=variant. Зато есть @subtype=parens. Т.е. если это вариант, то надо ставить @type=variant, @subtype=parens, а если это дигорская форма в скобочках, то @type=dialectal (это автоматически) и @subtype=parens. Исправил всё и в этих примерах, и в других.

Кстати, не понял, почему Вы здесь в дополнение к сноске (note@footnote) добавили вручную единичку внутри скобок. Она ведь вне скобок и у Абаева, т.е. ровно там, где у Вас и есть элемент note.
