### ISSUE TITLE
как посмотреть откуда хреф?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#27]
вот этого слова в словаре нет
![image](https://user-images.githubusercontent.com/13102259/158019240-655f2275-1597-4e5e-b529-42caedfbbe5d.png)
мне просто попалась ссылка на это слово, я просто два раза сделала хреф на qæw
![image](https://user-images.githubusercontent.com/13102259/158019271-f0a45ff7-8cbd-4efc-9139-c5fb5b1c70ed.png)

**Comment by obelyaev** [comment]
Ну да, это он просто иллюстрирует деривацию. Но обратите внимание, что слова разные: в нашем словаре файл qæwkkÆg, а у Вас – qæwkkAg.

Действительно, в т. 1 есть слово dykkag, где стоит ссылка на qæwkkæg. Я его удалил и заменил ссылку на qæw.
