### ISSUE TITLE
странный хреф, странная сноска, уточнение про цит

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#29]
Слово riwæ
![image](https://user-images.githubusercontent.com/13102259/160279517-a193b19e-cd2f-4c3d-82e1-93c33dc8f29e.png)

первое желтое я положила в ноут (но странные кавычки...), на ǧæzdug поставила хреф на иронское qæznyg (но в этом энтри нет упоминания слова ǧæzdugʒinadæ), ʒinadæ сделала просто m.

второе желтое (rai-) сделала иранский цит, правильно?

(третье желтое язык, записала в ишью с языками)

И в сноске тут сказано miwæ из *maiva, я сделала хреф на "mi", но там в этимологии maiva не упоминается...
![image](https://user-images.githubusercontent.com/13102259/160279623-3cec397e-59aa-4edd-8405-1be85ae3cf38.png)

**Comment by obelyaev** [comment]
Мда. Вроде бы всё сделали правильно (странный хреф – это, видимо, цитата из этого Гурдж.), а непоследовательность – это так в словаре, это от нас не зависит :)
