### ISSUE TITLE
в re не ставится точка с запятой между сенсами

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#31]
![image](https://user-images.githubusercontent.com/13102259/160643876-3ac8692b-7c12-4667-8e48-d561361ba704.png)
![image](https://user-images.githubusercontent.com/13102259/160644242-2b09a1b6-efb1-4adc-979b-23ea46f9ab62.png)
![image](https://user-images.githubusercontent.com/13102259/160644334-d3379463-c6f7-4b5a-b3eb-c22f78579281.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/161738284-939883cb-5fca-44cc-bd9f-09cb9e0db996.png)
![image](https://user-images.githubusercontent.com/13102259/161738321-a326f28c-d39d-46ed-8617-6e6e2f5851fd.png)

**Comment by obelyaev** [comment]
пофиксил
