### ISSUE TITLE
проблемы с хрефом

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#32]
![image](https://user-images.githubusercontent.com/13102259/160811373-5f596f91-fa06-432e-8bbf-94f77035a72d.png)
в общем здесь ccылка на rævæg, но само слово ræg. Если писать в хреф w "rævæg", то "см." все равно поставится?
![image](https://user-images.githubusercontent.com/13102259/160811477-3981f0ef-1ea4-4665-8f7b-b151eb999a9f.png)
![image](https://user-images.githubusercontent.com/13102259/160811419-1877d812-8081-4077-bf55-a51bdd3e40a5.png)

если что, сейчас "см." в любом случае не ставится, если перед хрефом стоит usg.
и тут еще почему-то две автоматические точки (возможно, из-за w?)

**Comment by obelyaev** [comment]
Вроде решил все проблемы, теперь "см." появляется где надо (и да, в том числе, если писать внутрь w).
