### ISSUE TITLE
проблемы со структурой (конфликт ноута и экзампла...)

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#33]
![image](https://user-images.githubusercontent.com/48504970/160849853-ca0ed2aa-2c66-4bb2-9caf-b771a4205111.png)
Вот здесь вот загадочное в example group - с одной стороны, комментарий идет к примеру выше, но потом идет двоеточие и примеры дальше как будто к сабэнтри в скобках...
И вот непонятно, куда девать этот ноут - внутрь примера? но тогда следующий пример идет с точкой с запятой, чего нет у Абаева. Просто после примера? Но тогда не получится вставить следующий экзампл... 

Поэтому я сделала это через re... Но не знаю, насколько это сомнительно)))

![image](https://user-images.githubusercontent.com/48504970/160852075-d6770fd1-fddc-4754-9a53-5ebf6cb74b97.png)

слово qarm

**Comment by obelyaev** [comment]
Хм, нет, там же примеры не на bawaʒyg, а на то же самое qarm. Посмотрите, там же нет корня waʒyg. Поэтому считать, что это такой re, у которого главное слово bawaʒyg īs, неправильно. Я думаю, что двоеточие – просто опечатка, надо делать это как note к предшествующему примеру и всё.

**Comment by jvsntsn** [comment]
переделала, закрываю
