### ISSUE TITLE
какой язык

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#34]
слово qarū
![image](https://user-images.githubusercontent.com/48504970/160869625-eb5ea8a5-1ac9-4355-9dcf-24664cf1a4d2.png)

в осетинском такого явно нет... балкарский? или тоже просто отправить в тюркские?

**Comment by obelyaev** [comment]
Посмотрел в старлинге (словарь А.В. Дыбо), форма qarɨ есть во многих тюркских, в том числе и в балкарском. Так что, наверное, тюрк. Можно, кстати, поставить два языка: тюрк. как основной и балк. как вторичный. Раз уж он тут рядом упоминается.

**Comment by jvsntsn** [comment]
сделала, закрываю
