### ISSUE TITLE
на всякий случай спрошу про ре

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#35]
![image](https://user-images.githubusercontent.com/13102259/161308700-ce5ba7bd-08b5-4a51-85ba-34a39357befe.png)
вот здесь явно ре, но нет тире. я предлагаю забить и пусть тире будет
![image](https://user-images.githubusercontent.com/13102259/161308756-53e09543-4ae0-4c22-b27f-a157234669ea.png)

**Comment by obelyaev** [comment]
Да, конечно. Оно и нагляднее отделяет ре от примеров.
