### ISSUE TITLE
проблемы с ре

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#36]
слово qæbær

1. 
![image](https://user-images.githubusercontent.com/48504970/161622036-92cfacd2-d910-4eee-bf49-1e2302a56e89.png)
вот здесь сначала идут ре, потом комментарий, который относится к лемме, потом еще один ре, и у меня не получается вставить ре после ноута, который не входит в состав предыдущей ре (что как бы логично); получается, что сначала идут все ре, а потом ноут (что тоже мне кажется нормальным, и я предлагаю забить и оставить так)

2. 
![image](https://user-images.githubusercontent.com/48504970/161622393-11274638-3619-4100-aa21-4e427063090f.png)
еще один ре идет после примеров, но у меня он вставляется в начало, к остальным ре... Пишет, что элемент после группы примеров поставить нельзя (хотя мне казалось, что раньше я когда-то ставила, и все было ок)

**Comment by obelyaev** [comment]
По первому пункту: да, не принципиально, но всё-таки правильно, чтобы элементы типа note (глобального класса) можно было вставлять где угодно. Поэтому я обновил модель, теперь можно. Исправил статью соответственно.

По второму пункту: у меня всё вставилось куда надо, не ругается. Уж не знаю, м.б. это как раз связано с моими изменениями в модель.
