### ISSUE TITLE
запуталась в mentioned

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#37]
Слово rūd
Вот здесь желтое не понимаю, как лучше оформить...
![image](https://user-images.githubusercontent.com/13102259/161689001-20b350a9-023f-4188-8b3d-4d5d47b6b5cf.png)
пока у меня так
![image](https://user-images.githubusercontent.com/13102259/161689068-f26bc877-4ede-4ba8-bb3d-76bce13cbdbb.png)

**Comment by obelyaev** [comment]
первое – как mentioned из иранского, второе я бы сделал всё-таки w (раз это энклитическое местоимение) согд. ман., третье – тоже иранское
