### ISSUE TITLE
цитата на немецком?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#38]
напомните, пожалуйста, как мы вот это оформляем?
![image](https://user-images.githubusercontent.com/13102259/161695643-80ab7f96-55b3-4761-899b-c0c50290907a.png)
Слово rūʒyng

и там где An ihrer не очень понятно, есть ли еще какие-то буквы

**Comment by obelyaev** [comment]
надо то, что в кавычках, cit > quote > q, а ссылку – внутри cit, bibl. Такъ будет правильно.

**Comment by obelyaev** [comment]
(я уже сделал)
