### ISSUE TITLE
не нашла хреф

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#39]
не нашла в словаре ничего похожее на bæzdajnæ :(
![image](https://user-images.githubusercontent.com/13102259/161724781-d12ff6e8-86a6-48df-8b6e-43a7fe2651bb.png)
плюс здесь еще странное оформление re через тире. забить же?

**Comment by obelyaev** [comment]
На второе забить, а вот про bæzdajnæ не знаю. Правда же нет такого слова. Дигорский словарь даёт альтернативные формы бӕздайнӕ, бӕздайӕн. Мне кажется, такие слова всё-таки надо добавлять (с атрибутом abv:status = new). Сейчас добавлю.

**Comment by obelyaev** [comment]
Добавил и поменял хреф.
