### ISSUE TITLE
опять какой-то сомнительный пример

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#42]
![image](https://user-images.githubusercontent.com/48504970/161839052-87f65f48-269a-496f-83c2-269377174ed3.png)
Опять что-то странное в примере... Пытаться как-то это туда впихнуть? Или ноутом куда-нибудь до, например?))

**Comment by jvsntsn** [comment]
Сделала вот так пока
![image](https://user-images.githubusercontent.com/48504970/161840431-f57d0725-42d9-4348-a862-dc63002f3e12.png)

**Comment by obelyaev** [comment]
Да, только надо одинарные кавычки, где "стой" (через rendition). А так нормально. Разве что может быть не очень правильным давать некорректно транскрибированный пример Палласа как осетинский. С другой стороны, формально это таки действительно пример на осетинском, так что можно оставить.
