### ISSUE TITLE
note в примере

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#43]
Слово ᵆrxændæg
![image](https://user-images.githubusercontent.com/13102259/161934546-3584e27d-d7c7-4bf6-be84-5591b2d3ca4a.png)

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/162832683-9e27f2d6-82db-4e2f-b396-4312ffa818ce.png)

слово qæstæ_2

**Comment by obelyaev** [comment]
Теперь всё отображается правильно
