### ISSUE TITLE
Огромный ноут, который у Абаева оформлен как пример...

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#44]
![image](https://user-images.githubusercontent.com/48504970/162281273-6cfb9fe5-4d30-49ac-ad16-6f6dd72b2bea.png)

Оставить так, как в оригинале? И вручную поставить точку и тире? Или просто сделать ноут без точки с тире (это же все-таки не пример, а комментарий)

**Comment by obelyaev** [comment]
Сделайте вручную точку и тире. Я думаю, их роль здесь – отделить ноут от перекрёстной ссылки перед ним.
