### ISSUE TITLE
постсабэнтри, который как бы постсенс без собственно вхождения

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#45]
Но со всеми другими атрибутами, в т.ч. примера, который очень удобно запихнуть в ре
![image](https://user-images.githubusercontent.com/48504970/162785688-ada22fe4-25a6-4fd7-8064-4acfb01ecd49.png)
слово qæstæ

но проблема, что оксиджен ругается, если убрать форм...

или не париться и сделать все ноутом?

**Comment by jvsntsn** [comment]
сделала по совету Иры экзампл груп с ноутом

**Comment by obelyaev** [comment]
Да, хорошее решение.
