### ISSUE TITLE
сенс не ставится после сабэнтри

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#47]
![image](https://user-images.githubusercontent.com/48504970/163235367-d9676e91-38f7-4bc1-a3a3-9fc4fb66edd7.png)

после ре не получается вставить еще сенс

**Comment by jvsntsn** [comment]
сделать просто ноутом?

**Comment by obelyaev** [comment]
Так именно так и надо, поэтому Абаев и сделал такой порядок.
