### ISSUE TITLE
ре или не ре?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#49]
![image](https://user-images.githubusercontent.com/48504970/163243035-42efde40-a0b6-4033-8ecb-3df440c76320.png)

вот здесь если сделать выражение как ре, то появится точка с запятой, которая не нужна
а если в ноуте как phr, то иронский/дигорский варианты не делают палочку...

**Comment by obelyaev** [comment]
Логичнее, конечно, re. Но это легко исправить: сделать re под sense, тогда точка с запятой не ставится (и структура получается логичная). Уже сделал.
