### ISSUE TITLE
ref_Макалатин-Макалатия?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#50]
![image](https://user-images.githubusercontent.com/48504970/163256865-27be21d2-95db-4692-aed1-e6bf253482b5.png)
вот здесь Макалатия, а в списке рефов забит Макалатин - это одно и то же? Или нет?

**Comment by jvsntsn** [comment]
(юбилейный ишью, ура))

**Comment by obelyaev** [comment]
Это я опечатался. Исправил в списке рефов
