### ISSUE TITLE
сабэнтри в сенс?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#6]
![image](https://user-images.githubusercontent.com/48504970/155696886-d46fba8c-ecfc-4033-9ef7-df56cd700529.png)
Вот здесь, с одной стороны, два сенсгруп; с другой - получается, что во втором сенсгруп - сабэнтри? Забить на номера сенсгруп и сделать их через комментарии?

**Comment by obelyaev** [comment]
Да, непростой случай. С одной стороны, Абаев трактует "одежду" как одно из значений этого слова (пусть и в ограниченном морфологическом контексте). С другой стороны, формально говоря, слово pysūl означает "тряпка", а значение "одежда" имеет слово pysūltæ, т.е. как раз-таки сабэнтри. На самом деле модель TEI позволяет включать элемент <re> внутрь <sense>, поэтому почему бы нет? Я могу это разрешить. Мне кажется, это будет лучшим вариантом.

**Comment by obelyaev** [comment]
Хм, Вы знаете, тут даже менять ничего не надо, потому что уже можно помещать сабэнтри в сенс. У меня там стоит "см. lasyn". Там, правда, формально другой случай: сабэнтри относятся к определённому значению слова. А здесь у Вас как будто бы сабэнтри само одновременно образуется значение. Не думаю, что это принципиально.

**Comment by jvsntsn** [comment]
Я сделала сабэнтри в сенс, но там стоит точка с запятой, которую нельзя убрать
![image](https://user-images.githubusercontent.com/48504970/155885337-16725fcc-650b-4144-85fd-8c482c9b326f.png)

**Comment by obelyaev** [comment]
Исправил, теперь нет точки с запятой (надо синхронизировать abaev-tei-oxygen)
