### ISSUE TITLE
ругается на extralang

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict-tei#7]
Почему-то в слове obaw ругается на extralang в mentioned, потом я делала несколько языков, и все было нормально
![image](https://user-images.githubusercontent.com/48504970/155886149-52ad4c60-d239-4df0-ac3b-21a2a37462c7.png)

**Comment by obelyaev** [comment]
Всё дело в том, что Вы добавили этот атрибут в сам элемент lang, а не в mentioned. Исправил.
