### ISSUE TITLE
языки

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict-tei#80]
Делаю новое ишью для языков

дард.
![image](https://user-images.githubusercontent.com/13102259/205879173-fb584315-23f3-4fbe-98f6-ee05c6f85123.png)

селькупский
![image](https://user-images.githubusercontent.com/13102259/205879290-c51761a8-950a-43cf-a8bc-52ee58eca82e.png)

**Comment by solanum-tuberosum** [comment]
слово typpyr
тур. (диал.)
![image](https://user-images.githubusercontent.com/13102259/207156767-92219b48-249d-4e34-86b6-4e3dd7740752.png)

**Comment by solanum-tuberosum** [comment]
Слово tymbyl
хауса, аранта
![image](https://user-images.githubusercontent.com/13102259/207357596-15e959e6-f92d-4c4b-8491-d0f864e9728d.png)
![image](https://user-images.githubusercontent.com/13102259/207357639-351967ba-e1e6-42af-b850-662635b1afe1.png)
(и там очень много вопросов к этому слову)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/215055282-ad617bb5-69f9-4a6a-ae14-590bf89cb673.png)

**Comment by solanum-tuberosum** [comment]
Слово tu
![image](https://user-images.githubusercontent.com/13102259/215269971-21a7db3e-da18-4409-bb09-d702027a45eb.png)

**Comment by solanum-tuberosum** [comment]
так, блин, тут явно анат. это язык)) надо проверить все "анат." потому что я могла их просто в ноут в каких-то местах класть.
![image](https://user-images.githubusercontent.com/13102259/215997553-9fc1d9f3-faae-427c-b929-2fe76773cc37.png)
здесь сейчас сделала просто языки анат. и балк. и поверх написала "тюрк. (анат.)" и "тюрк. (балк.)". А в английской версии как сделать?

**Comment by solanum-tuberosum** [comment]
не нашла гр. визант

![image](https://user-images.githubusercontent.com/13102259/216014098-c2451a7b-b480-4f2f-8dad-99cae5b38729.png)

**Comment by solanum-tuberosum** [comment]
русск. (сиб.)
![image](https://user-images.githubusercontent.com/13102259/216291088-89aff90d-4c9a-46db-ae52-5f5fee1ea17e.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/216304962-5e9e5a8c-a42e-4e51-9b3f-dd3af42734ad.png)

**Comment by solanum-tuberosum** [comment]
А это просто ноутом? или тоже надо добавить?
Слово tīw
![image](https://user-images.githubusercontent.com/13102259/216547222-7d3dbd54-0fd3-4286-9881-4be59e6a97d7.png)

**Comment by solanum-tuberosum** [comment]
такой же вопрос
![image](https://user-images.githubusercontent.com/13102259/216552605-10d37dcf-bfca-4472-9ba3-0dd55e3bb264.png)

**Comment by solanum-tuberosum** [comment]
Слово tillæg
![image](https://user-images.githubusercontent.com/13102259/216754845-eda64ac7-1073-4782-a40c-3bca8b77a101.png)

**Comment by solanum-tuberosum** [comment]
восточнотюрк
![image](https://user-images.githubusercontent.com/13102259/216759077-22b8ead8-454c-40e3-88d7-6299d7b496ba.png)

**Comment by solanum-tuberosum** [comment]
просто крым. нет. татар. (крым.)?
![image](https://user-images.githubusercontent.com/13102259/216774828-7fccd44d-35a5-4b6f-b219-25b01aaaa454.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/216809644-0b163458-3396-416c-a4e2-240aad28c923.png)

**Comment by solanum-tuberosum** [comment]
Слово tætær (и мои любимые проблемы с "анат."
![image](https://user-images.githubusercontent.com/13102259/216921972-d5817a79-02fc-4008-8254-6ca41b523f9a.png)

**Comment by solanum-tuberosum** [comment]
Слово tæryn 2
снова маратхи, кажется где-то уже было (плюс тут цыган. а в базе цыг., ок?)
![image](https://user-images.githubusercontent.com/13102259/216979655-d837f617-2c21-40d0-8db7-7072472f23fe.png)

**Comment by solanum-tuberosum** [comment]
Слово tæryn 1
![image](https://user-images.githubusercontent.com/13102259/217173052-a91374d9-6452-4bb8-bc6d-592cbab9fa92.png)

**Comment by obelyaev** [comment]
селькупский добавил как "селькуп.", абаевское длинное название надо вручную

евр. = др.евр.

**Comment by obelyaev** [comment]
пенджаби уже есть

**Comment by obelyaev** [comment]
> так, блин, тут явно анат. это язык)) надо проверить все "анат." потому что я могла их просто в ноут в каких-то местах класть.

Это анатолийский тюркский (турецкий), да

> здесь сейчас сделала просто языки анат. и балк. и поверх написала "тюрк. (анат.)" и "тюрк. (балк.)". А в английской версии как сделать?

Так же и сделать, у Абаева интенция, что это тюркские слова, но фактически он же цитирует два конкретных языка.

**Comment by obelyaev** [comment]
перс. (бахтиарский диалект) = перс. (бахтиар.) (уже есть)

**Comment by obelyaev** [comment]
> просто крым. нет. татар. (крым.)? 

да, конечно

**Comment by obelyaev** [comment]
цыг. ок

согд. хр. = согд. христ. в базе
